# Generated by Django 2.1.5 on 2019-01-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='YakesPorno',
            field=models.TextField(default='Lalochka'),
        ),
    ]
