# Generated by Django 2.1.5 on 2019-01-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_post_yakesporno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='YakesPorno',
            new_name='text',
        ),
    ]
